openapi: 3.0.1
info:
  title: WeatherAPI
  version: 1.0.0
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /weather:
    get:
      summary: Weather check
      description: Dummy API to check the weather
      parameters:
       -
        name: q
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - testKey
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - http://54.78.83.162:8888
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - https://run.mocky.io/v3/6b754fa8-3a58-40ee-8955-52932d6b9614
  type: http
x-wso2-basePath: /weather/1.0.0
x-wso2-transports:
 - http
 - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
